[package]
name = "buzuki-search"
version = "0.1.0"
authors = ["Panagiotis Ktistakis <panktist@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.1"
futures = "0.1.26"
hyper = "0.12.27"
lazy_static = "1.3.0"
log = "0.4.6"
regex = "1.1.5"
serde_json = "1.0.39"
tantivy = "0.9.1"
tempfile = "3.0.7"
url = "1.7.2"

[profile.release]
lto = true
opt-level = "s"
