[package]
name = "buzuki-search"
version = "0.1.0"
authors = ["Panagiotis Ktistakis <panktist@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.2"
futures = "0.1.28"
hyper = "0.12.33"
lazy_static = "1.3.0"
log = "0.4.8"
regex = "1.2.1"
serde_json = "1.0.40"
tantivy = "0.10.1"
tempfile = "3.1.0"
url = "2.1.0"

[profile.release]
lto = true
opt-level = "s"
